### ISSUE TITLE
Windows10, Compilation error

### ISSUE THREAD

**Issue by JakubesP** [ilyagrishkov/libtraceroute#18]
Dear ilyagrishkov,
when i try to use Your crate, I get the following error:
`linking withlink.exe failed: exit code: 1181 error: could not compilegui_tracert`

**Comment by JakubesP** [comment]
I am sorry, it was my fault.

**Comment by ilyagrishkov** [comment]
Dear @JakubesP. Glad you've found the solution for the problem. If you don't mind, could you comment how you solved it in case someone else has a similar issue.
